# Generated by Django 5.1.2 on 2024-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='availabilty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teachers',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teachers',
            name='firstName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teachers',
            name='lastName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teachers',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='teachers',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teachingPhilosophy',
            field=models.TextField(blank=True),
        ),
    ]
