# Generated by Django 5.1.2 on 2024-11-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='availabilty',
            new_name='availability',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='profilePicture',
        ),
    ]
