# Generated by Django 5.1.2 on 2024-11-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_availabilty_teachers_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='phoneNumber',
        ),
    ]
