# Generated by Django 5.1.2 on 2024-10-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='vidio_url',
            new_name='video_url',
        ),
    ]
