# Generated by Django 5.0.7 on 2024-08-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name_plural': 'Admins'},
        ),
    ]
