# Generated by Django 5.1.2 on 2024-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_customuser_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
